### PR TITLE
Add 'awair-pm' air quality tile calculation

### PR DESCRIPTION
**Pull request by deanlyoung**

### CODE REVIEW

**Comment by deanlyoung** [comment]
Here is a proposal of an 'air quality method' that I developed in https://github.com/deanlyoung/homebridge-awair-local that is handy for Air Filter automation using only Particulates. Most air purifiers don't have VOC filters or aren't good at reducing them. Triggering an air filter to run based on the Air Quality tile in HomeKit, which is comprised of TVOCs, Particulates, and other chemicals, isn't exactly helpful when the main cause of poor IAQ is a VOC or other chemical.

**Comment by deanlyoung** [comment]
Also fixed a couple of small typos and removed the air quality method 'awair-score' which appears was not implemented anyway.

**Comment by DMBlakeley** [comment]
Let me review as I am pretty sure that awair-score is implemented using 'score' value returned for API data call. Would propose adding awair-pm as an additional method rather than replacing awair-score.

**Comment by deanlyoung** [comment]
Ahh, right you are! I missed it because there wasn't a specific if-else clause for it. I forgot about that. But that's good and bad, I guess, since it should be easy to spot, but also need a fallback for a typo/no method.

**Comment by DMBlakeley** [comment]
Default method for `airQualityMethod` is set in index.js, line 43, `private airQualityMethod = 'awair-aqi';`

I'm pretty sure that I have defaults pretty well covered but certainly could use a second eye on the code.

**Comment by deanlyoung** [comment]
I just updated to make the cases more explicit, so each method should now include its own calculation, and it still falls back to 'awair-score' in the `else` clause.

**Comment by DMBlakeley** [comment]
I am pretty sure that I have successfully merged your PR with v5.7.2 along with updating README.md, CHANGLOG.md, package.json and package-lock.json to make v5.7.3. Let me know if you see any oops.

**Comment by DMBlakeley** [comment]
Found 1 small issue. For `awair-pm` need default for Glow and Glow-C. Setting to `awair-aqi` as I did for `nowcast-aqi`.

Pushing out as v5.8.0 as `awair-pm` is adding new functionality.

**Pull request merged**
